// Generated by dedot cli

import type { GenericSubstrateApi } from 'dedot/types';
import type { Bytes } from 'dedot/codecs';
import type { GenericContractEvents, GenericContractEvent } from 'dedot/contracts';

export interface ContractEvents<ChainApi extends GenericSubstrateApi> extends GenericContractEvents<ChainApi> {
  /**
   * A new slug mapping was created.
   *
   * @signature_topic: 0x158f3971ec2959a4691577ffa84e840235df7042fca7436d7b1c5da8fedb8550
   **/
  Shortened: GenericContractEvent<
    'Shortened',
    {
      /**
       * The slug of the mapping.
       *
       * @indexed: false
       **/
      slug: Bytes;
      /**
       * The URL that the slug maps to.
       *
       * @indexed: false
       **/
      url: Bytes;
    }
  >;

  /**
   * A pre-existing mapping was used.
   *
   * @signature_topic: 0x1d5bed68bd86daf899039efa5fc22aa452a9b86752bae8c91c5aaf1c44112a62
   **/
  Deduplicated: GenericContractEvent<
    'Deduplicated',
    {
      /**
       * The slug of the mapping.
       *
       * @indexed: false
       **/
      slug: Bytes;
      /**
       * The URL that the slug maps to.
       *
       * @indexed: false
       **/
      url: Bytes;
    }
  >;
}
