// Generated by dedot cli

import type { AccountId32, Bytes } from 'dedot/codecs';

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Link = { urls: InkStorageLazyMapping; slugs: InkStorageLazyMapping; upgrader?: AccountId32 | undefined };

export type InkPrimitivesLangError = 'CouldNotReadInput';

export type LinkSlugCreationMode =
  | { type: 'New'; value: Bytes }
  | { type: 'DeduplicateOrNew'; value: Bytes }
  | { type: 'Deduplicate' };

export type LinkShorteningOutcome = { type: 'Shortened' } | { type: 'Deduplicated'; value: Bytes };

export type LinkError = 'SlugUnavailable' | 'SlugTooShort' | 'UrlNotFound' | 'UpgradeDenied' | 'UpgradeFailed';

export type InkEnvNoChainExtension = null;
